### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by Reilif** [ros-naoqi/pepper_dcm_robot#2]
Hi guys,

did you rename pepper_dcm_robot to pepper_dcm_bringup? I cannot find the package for indigo.

Thank you

**Comment by nlyubova** [comment]
Hello, 
the package is called pepper_dcm_bringup, and pepper_dcm_robot is just a repository

**Comment by Reilif** [comment]
Ok. It would be helpful if you change the INSTALL section 

sudo apt-get install ros-indigo-pepper-dcm-robot

to 

sudo apt-get install ros-indigo-pepper-dcm-bringup

**Comment by nlyubova** [comment]
Thank you for your comment! 
it is done!
