### ISSUE TITLE
Pepper Error 712

### ISSUE THREAD

**Issue by lengagne** [ros-naoqi/pepper_dcm_robot#4]
Hi,

I tried to use ROS to move the base of the robot through the topic /cmd_vel.

After a few minutes (randomly), one sensor detects an obstacle and the robot does not want to move in the corresponding direction, although there is no obstacle. When I shutdown the robot, it says "ERROR 712".

Can you help me ?

Best regards

**Comment by nlyubova** [comment]
Hello, 
could you please try to command your robot with Naoqi Driver (http://wiki.ros.org/naoqi_driver)? it has the same cmd_vel topic.
Just start it as:
roslaunch naoqi_driver naoqi_driver.launch nao_ip:=<PEPPER_IP>

it would be interesting to know if you get the same issue. 

If yes, then please check the log on your Pepper:
ssh nao@<PEPPER_IP>
tail -f /var/log/naoqi/servicemanager/system.Naoqi.log

Let us know,
Natalia
