### ISSUE TITLE
Pepper planned movement does not match real execution

### ISSUE THREAD

**Issue by mzn723** [ros-naoqi/pepper_dcm_robot#5]
Hello,

There seems to be a problem that I don't exactly understand.
Using Moveit!, after planning a trajectory, the simulation seems to perform the correct planned movement, however after executing the presumably correct planned trajectory on the real robot the resulted movement is not correct (the robot moves joint by joint consecutively instead of simultaneously). 

Is this a problem from the launch file, the naoqi_dcm_driver itself, or could it be an incompatibility with my version of Pepper?

Did it work with anyone using Pepper?

**Comment by mzn723** [comment]
The problem is in naoqi_dcm_driver/src/robot.cpp: `Robot::writeJoints()` line 493. 
There is a `break;` that causes the program to call `Motion::writeJoints()` for each joint separately.

**Comment by awesomebytes** [comment]
I confirm, commenting out the `break;` makes it work.

**Comment by nlyubova** [comment]
Please, fix it here

**Comment by awesomebytes** [comment]
Can't fix it in this repo (given it just contains launch and config files), but I've submitted a PR: https://github.com/ros-naoqi/naoqi_dcm_driver/pull/6

**Comment by nlyubova** [comment]
Thanks !
